version: "3.9"

services:
  api:
    build: .
    container_name: express-redis-api
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
