version: '3.8'

services:
  db:
    image: mongo:4.1.13
    container_name: db
    networks:
      - net_A
    volumes:
      - db-data:/data/db
    ports:
      - '27017:27019'

networks:
  net_A:
    external: false
    name: net_A

volumes:
  db-data:
