#!/bin/sh

FRONTEND_NETWORK="frontend_network"
BACKEND_NETWORK="backend_network"

FRONTEND_IMAGE="frontend:1.0"
BACKEND_IMAGE="my-backend:1.0"
DB_IMAGE="database:1.0"

FRONTEND_CONTAINER="frontend"
BACKEND_CONTAINER="backend"
DB_CONTAINER="database"

FRONTEND_HOST_PORT=8080
FRONTEND_CONTAINER_PORT=80

BACKEND_HOST_PORT=3000
BACKEND_CONTAINER_PORT=3000

DB_CONTAINER_PORT=3306

DB_USER="root"
DB_PASSWORD="secret"
DB_NAME="testdb"
