version: "3.9"

services:
  # ---------- Express API ----------
  api:
    build: .
    container_name: api-service
    environment:
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgres://appuser:apppass@postgres:5432/appdb
      PORT: 3000
    depends_on:
      - redis
      - postgres
    networks:
      - backend

  # ---------- Redis ----------
  redis:
    image: redis:7-alpine
    container_name: redis-service
    networks:
      - backend

  # ---------- PostgreSQL ----------
  postgres:
    image: postgres:16-alpine
    container_name: postgres-service
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: appdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  # ---------- NGINX ----------
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:

